# Generated by Django 4.2.2 on 2023-08-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_advertisements_created_at_advertisements_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisements',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
