# Generated by Django 4.2.2 on 2023-08-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0003_alter_advertisements_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements',
            table='Объявления',
        ),
    ]
